Group_DTO(2)
f-lab-edu/my-neighbor pull request #12
Opened 2023-01-01 06:50 UTC by yrgell

* Conflict File 수정

2023-01-01 06:59 UTC, yrgell commented
* Group Repository(빈 파일) 생성
* Group.java 피드백 수정
* /target/ 파일 제거

2023-01-01 07:06 UTC, eyuna commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
사용하시는 IDE 에서 오류 발생하지 않나요?? 생성자 확인 부탁드립니다. :)

2023-01-01 07:26 UTC, yrgell commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
헉 group으로 수정했습니다

2023-01-01 07:48 UTC, eyuna commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
아직 push 는 안하신건가요?? 😃

그리고 Group 엔티티 안에 title, content 등등 필드는 포스팅 관련인 것 같은데
하나의 그룹에 포스팅 하나의 데이터가 들어가는 부분이 어떤 의도로 만드신건지 잘 이해가 되지 않습니다. 설명해주실 수 있을까요?

2023-01-01 07:52 UTC, yrgell commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
1. group_impl 로 새로 pr 생성했습니다
2. 포스팅도 그룹과 묶어서 DTO 생성하는줄 알았는데 별도로 분리할까요?

2023-01-01 09:37 UTC, f-lab-lyan commented
@yrgell 그런데, 이 PR이 진주님 메인에서 나왔어요. 아마도 머지하고 나면, 다시 reset하고, force-push하셔야 할 것 같네요. ㅜㅠ

2023-01-01 09:41 UTC, f-lab-lyan commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
<img width="526" alt="image" src="https://user-images.githubusercontent.com/90605505/210166552-20dd9ce5-11ed-4a81-add7-3befb597016c.png">

2023-01-01 09:53 UTC, f-lab-lyan commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
> 포스팅도 그룹과 묶어서 DTO 생성하는줄 알았는데 별도로 분리할까요?

일반적으로 DTO는 여러개의 Entity를 합쳐서 생성하는 경우도 있기 때문에 따로 분리하는 것이 좋을 것 같습니다. 제 느낌으로는 이건 아마도 Entity로 쓰이게 될 것 같은데요. 그렇다면, Group의 내용만 들어있는 것이 좋을 것 같습니다.

2023-01-01 12:17 UTC, yrgell commented
> @yrgell 그런데, 이 PR이 진주님 메인에서 나왔어요. 아마도 머지하고 나면, 다시 reset하고, force-push하셔야 할 것 같네요. ㅜㅠ

넵..... 제가 아직 브랜치 사용하는게 헷갈려하는 것 같습니다 ㅜㅜ

2023-01-01 12:19 UTC, yrgell commented on api/src/main/java/com/api/model/group/Group.java
> +    public  Contents(Long groupId, int categoryId, int cityId, int townId, int maxNum, String title, String contents, String profileImageUrl, String masterId, LocalDateTime writeAt){
넵 그러면 분리하도록 하겠습니다

2023-01-02 09:00 UTC, eyuna requested changes

2023-01-02 09:00 UTC, eyuna commented on api/api.iml
> +<?xml version="1.0" encoding="UTF-8"?>
iml 파일은 전부 삭제 부탁드립니다.

2023-01-02 12:38 UTC, closed without merging