spring version 추가
f-lab-edu/my-neighbor pull request #14
Opened 2023-01-01 10:27 UTC by eyuna

spring-boot-maven-plugin 에 자바 버전 명시

2023-01-01 11:04 UTC, f-lab-lyan requested changes
전반적으로 이렇게 하면 될 것 같습니다만, 한 가지 추가로 https://www.baeldung.com/spring-boot-starter-parent도 살펴보시면 좋을 것 같습니다. 어떤 게 더 유리할지 확인해 보시죠.

2023-01-01 11:04 UTC, f-lab-lyan commented on api/pom.xml
> +
이 property는 parent에 위치하는 것이 더 바람직해 보이고, `maven.compiler.source`, `maven.compiler.target`과 어떤 관계에 있는지 확인해 보시면 좋을 것 같네요.

2023-01-01 11:04 UTC, f-lab-lyan commented on api/pom.xml
> +                <version>${spring.version}</version>
여기에 버전을 줄 수도 있지만, `<dependencyManagement>`와 마찬가지로 `<pluginManagement>`도 있어요. 이 부분도 확인해 주세요.

2023-01-02 02:33 UTC, eyuna commented on api/pom.xml
> +
`maven.compiler.source`: 자바 언어 버전 명시
`maven.compiler.target`: 컴파일 된 클래스가 호환되는 JVM 버전

parent랑 같은 버전의 자바를 사용할거라서 해당 properties 제거하였습니다.

2023-01-02 02:34 UTC, eyuna commented on api/pom.xml
> +                <version>${spring.version}</version>
넵 부모 폼에 `<pluginManagement>` 추가했습니다 :)

2023-01-02 12:40 UTC, merged