Feat/exception handler
f-lab-edu/my-neighbor pull request #24
Opened 2023-02-01 14:15 UTC by eyuna

**1. exception handler**
- RestControllerAdvice 추가
- MessageSource properties, accessor bean 추가
- 각 Service 에서 데이터를 찾지 못한 경우 NotFoundException 발생하도록 변경

2023-02-01 14:22 UTC, f-lab-lyan requested changes
익셉션이 발생했을 때, 메세지가 제대로 나오는지 확인이 필요할 것 같은데요. 혹시 테스트 코드 추가해 주실 수 있을까요?

2023-02-03 01:35 UTC, f-lab-lyan commented on api/src/test/java/com/api/GeneralExceptionHandlerTest.java
> +        MessageUtils.setMessageSourceAccessor(messageSourceAccessor);
이 부분이 궁금했는데요. MessageUtils를 쓰기 위해서 항상 MessageSourceAccessor를 넣어줘야하는데, 이걸 실제 코드에서는 어떻게 설정할 예정인가요?

2023-02-03 04:59 UTC, eyuna commented on api/src/test/java/com/api/GeneralExceptionHandlerTest.java
> +        MessageUtils.setMessageSourceAccessor(messageSourceAccessor);
@f-lab-lyan `ServiceConfig` 에서 MessageSourceAccessor 객체 를 생성하고 `MessageUtils.setMessageSourceAccessor()` 로 static MessageSourceAccessor 를 설정하게 했습니다.

2023-02-03 05:21 UTC, jongyoul commented on api/src/main/java/com/api/error/NotFoundException.java
> +    }
아예 메세지를 NotFoundException만들 때, 주는게 더 좋을 것 같다는 생각이 드는데 어떠세요? ServiceConfig에서 설정하는 것이 동작하기는 하지만, 약간 트릭 같은 느낌을 지울 수가 없네요 :-)

2023-02-03 05:23 UTC, f-lab-lyan commented on api/src/main/java/com/api/error/NotFoundException.java
> +    }
아예 메세지를 NotFoundException만들 때, 주는게 더 좋을 것 같다는 생각이 드는데 어떠세요? ServiceConfig에서 설정하는 것이 동작하기는 하지만, 약간 트릭 같은 느낌을 지울 수가 없네요 :-)

2023-02-04 04:13 UTC, eyuna commented on api/src/main/java/com/api/error/NotFoundException.java
> +    }
넵 MessageSource 없이 메세지에 들어갈 값을 주는걸로 변경했습니다. 😃

2023-02-05 09:39 UTC, merged

2023-02-05 12:10 UTC, f-lab-lyan commented
이미 머지 하셨지만, 괜찮네요. :-)