Group Controller - Response Body (2)
f-lab-edu/my-neighbor pull request #7
Opened 2022-12-27 11:17 UTC by yrgell

Group 모듈 Response Body 생성
- 그룹 삭제
- 그룹 포스팅 조회/특정 조회/작성/삭제/수정

2022-12-27 12:24 UTC, jongyoul requested changes
고치셔야 하는 파일은 제대로 고쳐졌는데, git에 포함되면 안되는 파일들이 포함된 것 같아요. 이 부분만 해결해 주시면 좋을 것 같습니다.

2022-12-27 12:24 UTC, jongyoul commented on .gitignore
> +>>>>>>> upstream/main
이 부분은 아마도 conflict이 난 상황 같아요. intelliJ에서 이 파일을 여시면 IDE가 어떻게 고칠 수 있는 지 알려줄 것 같네요. 해 보시고 잘 안되는 부분이 있으면 알려주세요.

2022-12-27 12:24 UTC, jongyoul commented on api/.gitignore
> +/target/
이 부분은 root의 .gitignore에 `**/target`을 추가히시면 동일한 효과를 보실 수 있을 것 같습니다.

2022-12-27 12:24 UTC, jongyoul commented on .gitignore
> +>>>>>>> upstream/main
그리고 아래에 보면, `.project`, `.settings`등의 디렉토리가 포함되어 있는데요. 해당 디렉토리는 이클립스용 디렉토리 같아 보여요. 이 부분도 `.gitignore`에 추가하시면 좋을 것 같습니다. git commit 하시기 전에 git status를 보시면, 어떤 파일들이 추가될 지 알 수 있으니, 커밋하시기 전에 확인해 보는 것도 좋을 것 같습니다.

2022-12-27 12:24 UTC, jongyoul commented on api/src/main/java/com/api/controller/group/GroupController.java
> +                "           \"groupId\": " + groupId + ", \n" +
👍

2022-12-27 12:24 UTC, jongyoul commented on api/src/main/java/com/api/controller/group/GroupRestController.java
> +package com.api.controller.group;
이 파일은 이름이 GroupRestController에서 GrouController로 바뀐 것 같은데, 아직 반영이 안된 것 같네요. 확인해 주실 수 있을까요?

2022-12-31 03:08 UTC, f-lab-lyan commented on .gitignore
> +>>>>>>> upstream/main
여기 보시면, conflict가 발생했던 흔적이 보이네요. 확인해 주시겠어요?

2022-12-31 03:08 UTC, f-lab-lyan commented on .gitignore
> +*.classpath
nit: Please add a new line at the end of the file

2022-12-31 03:09 UTC, f-lab-lyan commented on api/.gitignore
> +/target/
위에 `**/target`을 추가했으니, 이 파일은 없애도 되는 것이 아닌가요?

2022-12-31 03:09 UTC, f-lab-lyan commented on api/src/main/java/com/api/model/group/Group.java
> +
nit: Please remove empty lines between class definition and class variables.

2022-12-31 03:10 UTC, f-lab-lyan commented on api/src/main/java/com/api/model/group/Group.java
> +    }
이 컨스트럭터의 정체는? :-)

2022-12-31 03:11 UTC, f-lab-lyan requested changes
.gitignore 파일에 두 분이 사용하지 않는 IDE도 있는 것 같아요. 그 부분들은 찾아서 지워주면 좋을 것 같습니다.

2022-12-31 05:51 UTC, yrgell commented on api/src/main/java/com/api/model/group/Group.java
> +    }
그룹 포스팅 시 활용하려고 했는데 비효율적일까요?

2022-12-31 08:11 UTC, closed without merging